package lt.vu.psk.mybatis.model;

import lombok.Getter;
import lombok.Setter;

import java.util.List;

@Getter
@Setter
public class Municipality {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MUNICIPALITY.ID
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MUNICIPALITY.MUNICIPALITY_COUNTRY_NAME
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    private String municipalityCountryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MUNICIPALITY.MUNICIPALITY_NAME
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    private String municipalityName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MUNICIPALITY.ID
     *
     * @return the value of PUBLIC.MUNICIPALITY.ID
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MUNICIPALITY.ID
     *
     * @param id the value for PUBLIC.MUNICIPALITY.ID
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MUNICIPALITY.MUNICIPALITY_COUNTRY_NAME
     *
     * @return the value of PUBLIC.MUNICIPALITY.MUNICIPALITY_COUNTRY_NAME
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    public String getMunicipalityCountryName() {
        return municipalityCountryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MUNICIPALITY.MUNICIPALITY_COUNTRY_NAME
     *
     * @param municipalityCountryName the value for PUBLIC.MUNICIPALITY.MUNICIPALITY_COUNTRY_NAME
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    public void setMunicipalityCountryName(String municipalityCountryName) {
        this.municipalityCountryName = municipalityCountryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MUNICIPALITY.MUNICIPALITY_NAME
     *
     * @return the value of PUBLIC.MUNICIPALITY.MUNICIPALITY_NAME
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    public String getMunicipalityName() {
        return municipalityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MUNICIPALITY.MUNICIPALITY_NAME
     *
     * @param municipalityName the value for PUBLIC.MUNICIPALITY.MUNICIPALITY_NAME
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    public void setMunicipalityName(String municipalityName) {
        this.municipalityName = municipalityName;
    }

    public List<Tree> treeList;
}