package lt.vu.psk.mybatis.model;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class Tree {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TREE.ID
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TREE.TREE_NAME
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    private String treeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TREE.FOREST_ID
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    private Integer forestId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TREE.ID
     *
     * @return the value of PUBLIC.TREE.ID
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TREE.ID
     *
     * @param id the value for PUBLIC.TREE.ID
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TREE.TREE_NAME
     *
     * @return the value of PUBLIC.TREE.TREE_NAME
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    public String getTreeName() {
        return treeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TREE.TREE_NAME
     *
     * @param treeName the value for PUBLIC.TREE.TREE_NAME
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    public void setTreeName(String treeName) {
        this.treeName = treeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TREE.FOREST_ID
     *
     * @return the value of PUBLIC.TREE.FOREST_ID
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    public Integer getForestId() {
        return forestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TREE.FOREST_ID
     *
     * @param forestId the value for PUBLIC.TREE.FOREST_ID
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    public void setForestId(Integer forestId) {
        this.forestId = forestId;
    }
}