package lt.vu.psk.mybatis.model;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class TreesMunicipalities {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TREES_MUNICIPALITIES.MUNICIPALITY_ID
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    private Integer municipalityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.TREES_MUNICIPALITIES.TREE_ID
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    private Integer treeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TREES_MUNICIPALITIES.MUNICIPALITY_ID
     *
     * @return the value of PUBLIC.TREES_MUNICIPALITIES.MUNICIPALITY_ID
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    public Integer getMunicipalityId() {
        return municipalityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TREES_MUNICIPALITIES.MUNICIPALITY_ID
     *
     * @param municipalityId the value for PUBLIC.TREES_MUNICIPALITIES.MUNICIPALITY_ID
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    public void setMunicipalityId(Integer municipalityId) {
        this.municipalityId = municipalityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.TREES_MUNICIPALITIES.TREE_ID
     *
     * @return the value of PUBLIC.TREES_MUNICIPALITIES.TREE_ID
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    public Integer getTreeId() {
        return treeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.TREES_MUNICIPALITIES.TREE_ID
     *
     * @param treeId the value for PUBLIC.TREES_MUNICIPALITIES.TREE_ID
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    public void setTreeId(Integer treeId) {
        this.treeId = treeId;
    }
}