package lt.vu.psk.mybatis.dao;

import java.util.List;
import lt.vu.psk.mybatis.model.Forest;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ForestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOREST
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOREST
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    int insert(Forest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOREST
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    Forest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOREST
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    List<Forest> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.FOREST
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    int updateByPrimaryKey(Forest record);
}