package lt.vu.psk.mybatis.dao;

import java.util.List;
import lt.vu.psk.mybatis.model.TreesMunicipalities;
import org.apache.ibatis.annotations.Param;
import org.mybatis.cdi.Mapper;

@Mapper
public interface TreesMunicipalitiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TREES_MUNICIPALITIES
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    int insert(TreesMunicipalities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TREES_MUNICIPALITIES
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    List<TreesMunicipalities> selectAll();

    int getResultCountByTreeAndMunicipalityId(@Param("treeId") Integer treeId, @Param("municipalityId") Integer municipalityId);
}