package lt.vu.psk.mybatis.dao;

import java.util.List;
import lt.vu.psk.mybatis.model.Tree;
import org.mybatis.cdi.Mapper;

@Mapper
public interface TreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TREE
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TREE
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    int insert(Tree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TREE
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    Tree selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TREE
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    List<Tree> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.TREE
     *
     * @mbg.generated Mon May 15 02:02:29 EEST 2023
     */
    int updateByPrimaryKey(Tree record);

    Tree findByName(String treeName);

    int getResultCountByTreeName(String treeName);
}